aiven/inkless

core/src/main/scala/kafka/server/ReplicaManager.scala

Merger is getting stuck for unknown reason using PG control plane. Let's disable it until it is fixed.

chore(inkless): disable merger

---

storage/inkless/src/main/java/io/aiven/inkless/config/InklessConfig.java
storage/inkless/src/main/java/io/aiven/inkless/produce/AppendHandler.java
storage/inkless/src/main/java/io/aiven/inkless/produce/FileCommitter.java
storage/inkless/src/main/java/io/aiven/inkless/produce/Writer.java
storage/inkless/src/test/java/io/aiven/inkless/config/InklessConfigTest.java
storage/inkless/src/test/java/io/aiven/inkless/produce/FileCommitterTest.java
storage/inkless/src/test/java/io/aiven/inkless/produce/WriterIntegrationTest.java

Cached thread polls are unbounded. As concurrent uploads wait for commits to complete, the amound of uploads can grow without limits, affecting cpu utilization and increasing latencies. To bound the uploads to the expected commit latencies, this PR proposes to use fixed thread pool (8 by default) to be able to upload up to 8 files concurrently, these uploads have a P99 of 400ms on S3. As sequential commits can have a P99 of 50ms on PG, having 8 commits queued would already account for doubling the upload time. This is an initial estimation and the values could be updated and the defaults changed as this setup is tested; but having configurable thread pools should benefit in the long term.
Some examples on memory usage:
Without fixed pool:
With fixed pool:

refactor(inkless): use fixed thread pools for upload/cache

---

storage/inkless/src/main/java/io/aiven/inkless/produce/ActiveFile.java
storage/inkless/src/main/java/io/aiven/inkless/produce/ClosedFile.java
storage/inkless/src/test/java/io/aiven/inkless/produce/ClosedFileTest.java

Start time is measured on initialization which has wrong values: when an active file is initialized at the startup (leading to very large initial start time); and similarly if there is a period of no writes, the last rotation will start the counter at a very far time. To measure this correctly, only initialize on the first add to the batch.

fix(inkless): set file start time properly

---

storage/inkless/src/main/java/io/aiven/inkless/config/InklessConfig.java
storage/inkless/src/main/java/io/aiven/inkless/produce/AppendCompleter.java
storage/inkless/src/main/java/io/aiven/inkless/produce/AppendHandler.java
storage/inkless/src/main/java/io/aiven/inkless/produce/FileCommitter.java
storage/inkless/src/main/java/io/aiven/inkless/produce/FileCommitterMetrics.java
storage/inkless/src/main/java/io/aiven/inkless/produce/Writer.java
storage/inkless/src/test/java/io/aiven/inkless/config/InklessConfigTest.java
storage/inkless/src/test/java/io/aiven/inkless/produce/AppendCompleterTest.java
storage/inkless/src/test/java/io/aiven/inkless/produce/FileCommitterTest.java
storage/inkless/src/test/java/io/aiven/inkless/produce/WriterIntegrationTest.java
storage/inkless/src/test/java/io/aiven/inkless/produce/WriterPropertyTest.java

Instead of running this as a separate thread, run directly on the same thread as it is not an IO task.
Reduces thread allocation.

refactor(inkless): run append completer directly

---

build.gradle
core/src/main/scala/kafka/server/ReplicaManager.scala
core/src/main/scala/kafka/server/metadata/InklessMetadataView.scala
core/src/test/scala/unit/kafka/server/ReplicaManagerTest.scala
storage/inkless/src/main/java/io/aiven/inkless/config/InklessConfig.java
storage/inkless/src/main/java/io/aiven/inkless/control_plane/ControlPlane.java
storage/inkless/src/main/java/io/aiven/inkless/control_plane/EnforceRetentionRequest.java
storage/inkless/src/main/java/io/aiven/inkless/control_plane/EnforceRetentionResponse.java
storage/inkless/src/main/java/io/aiven/inkless/control_plane/InMemoryControlPlane.java
storage/inkless/src/main/java/io/aiven/inkless/control_plane/MetadataView.java
storage/inkless/src/main/java/io/aiven/inkless/control_plane/postgres/EnforceRetentionJob.java
storage/inkless/src/main/java/io/aiven/inkless/control_plane/postgres/PostgresControlPlane.java
storage/inkless/src/main/java/io/aiven/inkless/control_plane/postgres/PostgresControlPlaneMetrics.java
storage/inkless/src/main/java/io/aiven/inkless/delete/RetentionEnforcementScheduler.java
storage/inkless/src/main/java/io/aiven/inkless/delete/RetentionEnforcer.java
storage/inkless/src/main/java/io/aiven/inkless/delete/RetentionEnforcerMetrics.java
storage/inkless/src/main/resources/db/migration/V4__Retention_enforcement.sql
storage/inkless/src/test/java/io/aiven/inkless/control_plane/AbstractControlPlaneTest.java
storage/inkless/src/test/java/io/aiven/inkless/control_plane/postgres/EnforceRetentionJobTest.java
storage/inkless/src/test/java/io/aiven/inkless/delete/RetentionEnforcementSchedulerTest.java
storage/inkless/src/test/java/io/aiven/inkless/delete/RetentionEnforcerTest.java

This PR adds retention by time and size (`retention.ms`, `retention.bytes`) to the both control planes and its support on the broker side.
Note to the reviewer: I tried to decompose this into logical separate commits, should be easier to review step-by-step.

Add retention by time and size [INK-251]

---

storage/inkless/src/main/java/io/aiven/inkless/control_plane/postgres/DeleteRecordsJob.java
storage/inkless/src/main/java/io/aiven/inkless/control_plane/postgres/EnforceRetentionJob.java
storage/inkless/src/main/java/io/aiven/inkless/control_plane/postgres/FunctionResultProcessor.java
storage/inkless/src/main/resources/db/migration/V5__Fix_deadlock_in_delete_records_v1.sql
storage/inkless/src/test/java/io/aiven/inkless/control_plane/postgres/DeleteRecordsJobTest.java

The function did the deadlock-preventing ordering on a wrong query.
The job test was enhanced to check different request orders work correctly.
`EnforceRetentionJob` already had the code for processing results of such a PG function, which was generalized to serve both.

Fix deadlock in delete_records_v1 [INK-260]

---

.github/workflows/inkless-nightly.yml

Include release branches into the CI nightly to run all tests on these.

chore(ci): add inkless version branches to CI nightly

---

storage/inkless/src/main/resources/db/migration/V6__Improve_understandability_of_delete_topic_v1.sql

This commit slightly speeds up `delete_topic_v1` and `delete_records_v1` by using `WHERE NOT EXISTS` instead of `LEFT JOIN ... WHERE ... IS NULL`. This is also more explicit and easier to understand.
Another understandability change is using explicit locking on log records before deleting them in `delete_topic_v1`. This allows to revert `fk_batches_logs` to the default deferrability mode and not think about how constraint deferring works.
The semantics remains unchanged.

Speed up and improve understandability of delete_topic_v1 and delete_records_v1

---

core/src/main/scala/kafka/server/BrokerServer.scala
core/src/main/scala/kafka/server/metadata/InklessMetadataView.scala
core/src/test/scala/kafka/server/metadata/InklessMetadataViewTest.scala

Null values cause the LogConfig initialization using Properties.putAll to fail.
This is now spotted by using the LogConfig on the RetentionEnforcer and the newly added internal config internal.segment.bytes which is null by default, leading to NPE.

fix(inkless): Filter out null values from default configs

---

core/src/test/java/kafka/server/InklessClusterTest.java
storage/inkless/src/main/java/io/aiven/inkless/control_plane/postgres/FindBatchesJob.java
storage/inkless/src/main/java/io/aiven/inkless/control_plane/postgres/PostgresControlPlane.java
storage/inkless/src/main/resources/db/migration/V7__Find_batches_function.sql
storage/inkless/src/test/java/io/aiven/inkless/control_plane/postgres/FindBatchesJobTest.java

Define a new find_batches_v1 PG function for finding batches from all requested partition.
New implementation of `FindBatchesJob` now also supports limiting by `max.partition.fetch.bytes`.

Optimize FindBatchesJob for PostgresControlPlane [INK-45]

---

Makefile
docker/docker_build_test.py
docker/examples/docker-compose-files/inkless/.env
docker/examples/docker-compose-files/inkless/Makefile
docker/examples/docker-compose-files/inkless/docker-compose.demo.yml
docker/examples/docker-compose-files/inkless/docker-compose.yml
docker/inkless/Dockerfile

Set of fixes to inkless demo to allow passing the kafka version to the image.
This is useful when trying to test a specific version (e.g. 4.0.0-inkless).

fix(inkless:demo): allow to pass version

---

storage/inkless/src/main/java/io/aiven/inkless/control_plane/postgres/HikariMetricsTracker.java
storage/inkless/src/main/java/io/aiven/inkless/control_plane/postgres/PostgresControlPlane.java

Understanding better the initial issue with the metrics initialization, I'd propose to cleanup Hikari metrics.

refactor(inkless): clean up initialization to avoid this-scape error on JDK23

---

.github/workflows/inkless.yml

JDK17 is used on validation phase, and artifacts are reused on other jdks phases.
JOOQ classes if <21 they don't contain annotations to avoid `this-escape` compilation errors.
Adding JOOQ regeneration to avoid this.

fix(inkless:ci): regerate jooq classes when not on jdk17

---

core/src/main/scala/kafka/log/LogManager.scala
core/src/main/scala/kafka/server/BrokerServer.scala
storage/inkless/src/main/java/io/aiven/inkless/cache/InfinispanCache.java
storage/inkless/src/main/java/io/aiven/inkless/cache/ObjectCache.java
storage/inkless/src/main/java/io/aiven/inkless/common/SharedState.java
storage/inkless/src/main/java/io/aiven/inkless/config/InklessConfig.java
storage/inkless/src/test/java/io/aiven/inkless/cache/InfinispanCacheTest.java
storage/inkless/src/test/java/io/aiven/inkless/config/InklessConfigTest.java
storage/inkless/src/test/java/io/aiven/inkless/delete/FileCleanerIntegrationTest.java
storage/inkless/src/test/java/io/aiven/inkless/merge/FileMergerIntegrationTest.java
storage/inkless/src/test/java/io/aiven/inkless/merge/FileMergerMockedTest.java

Enable Infinispan passivation feature that permits to use local disk as a second tier for cache entries.
By default, it reuses the log directory, so there is no need to create another volume and reuses the same storage as classic kafka. It adds a couple of knobs: lifespan and maxIdle to be used as a proxy on the amount of space cache entries could use.

feat(inkless): add persistent storage for infinispan

---

core/src/main/scala/kafka/server/KafkaApis.scala
storage/inkless/src/main/java/io/aiven/inkless/metadata/InklessTopicMetadataTransformer.java
storage/inkless/src/test/java/io/aiven/inkless/metadata/InklessTopicMetadataTransformerTest.java

Inkless Partition leaders are assigned using a round-robin mechanism per request.
This means all topic partitions on the same response will be assigned the same leader based on the client AZ if possible (if available and matching with brokers).
Currently, all round-robin variables are initialized at zero. When many brokers are on the same AZ, this initialization happens to skew the load towards some of the brokers causing uneven load distribution and unpredictable performance depending on the broker serving the requests.
To fix this, the brokerId is being used to initialize the round-robin, so leaders will be spread more evenly.
Distribution of produce requests with current initialization:
Distribution of produce requests with fixed initialization:

refactor(inkless): initialize round-robin with brokerId

---

core/src/main/scala/kafka/server/DelayedFetch.scala
core/src/test/scala/integration/kafka/server/DelayedFetchTest.scala

Fix the following tests:
DelayedFetchTest.testDelayedFetchWithMessageOnlyHighWatermark endOffset=0
DelayedFetchTest.testDelayedFetchWithMessageOnlyHighWatermark endOffset=500
DelayedFetchTest.testDivergingEpoch()
DelayedFetchTest.testFetchWithFencedEpoch()
DelayedFetchTest.testNotLeaderOrFollower()
ReplicaManagerQuotasTest.testCompleteInDelayedFetchConsumerFetch()
ReplicaManagerQuotasTest.testCompleteInDelayedFetchWithReplicaThrottling()

fix broken tests after changes in DelayedFetch

---

.github/workflows/ci.yml

Start to run full CI workflow for Inkless and allow manual trigger for testing.

chore(inkless:ci): enable CI workflow for inkless branches

---

core/src/main/scala/kafka/server/BrokerServer.scala
core/src/main/scala/kafka/server/metadata/InklessMetadataView.scala
core/src/main/scala/kafka/server/metadata/KRaftMetadataCache.scala
core/src/test/scala/kafka/server/metadata/InklessKRaftMetadataCacheTest.java
core/src/test/scala/kafka/server/metadata/InklessMetadataViewTest.scala
metadata/src/main/java/org/apache/kafka/controller/ReplicationControlManager.java
metadata/src/test/java/org/apache/kafka/controller/ReplicationControlManagerTest.java

Server default is constantly used to verify if a topic is inkless or not.
To avoid this repeated work, store always the inkless enabled config on KRaft and rely on this to serve this check.

refactor(inkless): store inkless enabled config on KRaft

---

core/src/test/scala/unit/kafka/server/ReplicaManagerTest.scala

There is a class casting exception after the last commit caused by KRaftMetadataCache being expected on ReplicaManager. This is a temporal fix, as there are some pending refactoring to avoid the need to use a concrete class and rely on MetadataCache directly.

fix(inkless): enforce KRaftMetadataCache on ReplicaManagerTest

---

.github/workflows/build.yml
build.gradle

Had to downgrade the checks JDK to 17, as it is for some reason always generating (or using cached) classes with this-escape.
I tried different workarounds but will just leave it as a comment for now, as the tests _are_ running on both JDKs 17 and 23.

fix(inkless:ci): regenerate jooq classes with jdk23 on kafka ci

---

build.gradle

A couple more modules need to have the inkless testing modules avialable to run integration tests.

fix(inkless:build): add missing integration test inkless deps

---

core/src/main/scala/kafka/server/ReplicaManager.scala
core/src/test/scala/unit/kafka/server/ReplicaManagerTest.scala
storage/inkless/src/main/java/io/aiven/inkless/consume/FindBatchesJob.java
storage/inkless/src/main/java/io/aiven/inkless/consume/Reader.java
storage/inkless/src/test/java/io/aiven/inkless/consume/FindBatchesJobTest.java

Fetch requests might not contain the topic id. Retrieve the topic id from KRaft metadata if available

Ensure that inkless fetch  requests always contain the topic id

---

storage/inkless/src/main/java/io/aiven/inkless/produce/FileCommitJob.java
storage/inkless/src/main/java/io/aiven/inkless/produce/FileCommitter.java
storage/inkless/src/main/java/io/aiven/inkless/produce/FileCommitterMetrics.java
storage/inkless/src/main/java/io/aiven/inkless/produce/FileUploadException.java
storage/inkless/src/test/java/io/aiven/inkless/produce/FileCommitterTest.java

Identify errors by accumulating occurance of failed writes vs writes completed; and introduce specific rates for uploads (remote storage based), and commits (batch coordinator based) errors.
Also, use Meter as other Metrics instrumentations instead of Gauge.

feat(inkless): add error rate metrics for file committer

---

storage/inkless/src/main/java/io/aiven/inkless/consume/FileFetchJob.java
storage/inkless/src/main/java/io/aiven/inkless/merge/FileMerger.java
storage/inkless/src/main/java/io/aiven/inkless/storage_backend/azure/AzureBlobStorage.java
storage/inkless/src/main/java/io/aiven/inkless/storage_backend/common/ObjectFetcher.java
storage/inkless/src/main/java/io/aiven/inkless/storage_backend/gcs/GcsStorage.java
storage/inkless/src/main/java/io/aiven/inkless/storage_backend/in_memory/InMemoryStorage.java
storage/inkless/src/main/java/io/aiven/inkless/storage_backend/s3/S3Storage.java
storage/inkless/src/test/java/io/aiven/inkless/config/ConfigTestStorageBackend.java
storage/inkless/src/test/java/io/aiven/inkless/consume/CacheFetchJobTest.java
storage/inkless/src/test/java/io/aiven/inkless/consume/FileFetchJobTest.java
storage/inkless/src/test/java/io/aiven/inkless/merge/FileMergerMockedTest.java
storage/inkless/src/test/java/io/aiven/inkless/storage_backend/azure/integration/AzureBlobStorageMetricsTest.java
storage/inkless/src/test/java/io/aiven/inkless/storage_backend/common/fixtures/BaseStorageTest.java
storage/inkless/src/test/java/io/aiven/inkless/storage_backend/gcs/integration/GcsStorageMetricsTest.java
storage/inkless/src/test/java/io/aiven/inkless/storage_backend/in_memory/InMemoryStorageTest.java
storage/inkless/src/test/java/io/aiven/inkless/storage_backend/s3/integration/S3StorageMetricsTest.java

This allows to allocate ByteBuffers and reduce amount of byte array copying.
Tested with GCS client.
Pre:
Post:

storage: change fetch API to return ReadableByteChannel

---

docs/inkless/FAQ.md

Having fell for bad write latencies by testing with just a single producer and partition, I thought it'd be prudent to document the gotcha and cause/effect/suggestion

MINOR: Capture single-client gotcha

---

storage/inkless/src/main/java/io/aiven/inkless/consume/FetchPlanner.java
storage/inkless/src/main/java/io/aiven/inkless/consume/InklessFetchMetrics.java
storage/inkless/src/main/java/io/aiven/inkless/consume/Reader.java
storage/inkless/src/test/java/io/aiven/inkless/consume/FetchPlannerTest.java

Consumer fetch requests require a fan-out in number of batches to include to serve them. These batches may be across multiple objects.
Adding histogramns to measure how do these fan-outs look like: partitions per request, batches per partitions, objects per request.

refactor(inkless): add fetch fan-out metrics

---

core/src/main/scala/kafka/server/KafkaApis.scala
storage/inkless/src/main/java/io/aiven/inkless/metadata/ClientAzAwarenessMetrics.java
storage/inkless/src/main/java/io/aiven/inkless/metadata/InklessTopicMetadataTransformer.java
storage/inkless/src/test/java/io/aiven/inkless/metadata/ClientAzAwarenessMetricsTest.java

Successfully mapping client-provided AZ to a set of brokers is a key feature to optimize costs for diskless topics.
Adding metrics allows monitoring how much use of this feature is being activated by client configurations, and how balanced are the AZs.

feat(inkless): add metrics for client-az hit/miss
